### ISSUE TITLE
Consider documentation website?

### ISSUE THREAD

**Issue by jcbhmr** [btzy/nativefiledialog-extended#105]
**It doesn't have to be big!** I want to make that _very_ clear. Even a tiny landing page would be sufficient.

Why this might be a good idea:
- Google SEO. GitHub project readmes have _okish_ SEO. GitHub wikis have almost zero. They don't seem to be indexed very well 
  ![image](https://github.com/btzy/nativefiledialog-extended/assets/61068799/8f9e6c04-1180-4280-820d-75aa011f54c8)
- Putting more detailed docs _outside_ the readme. This is more of an organizational thing to keep the readme sort of like an "index page" that outsources to the developer-focused "how does this work" (GitHub wiki) and "how do I contribute" (CONTRIBUTING.md) and the user-focused "how do I use this" (docs website) places.
- Encourage more examples! Having a place to put examples that makes them look nice and pretty with prose explainer text and/or **images too** next to them is good!
- Document the API a little more effectively. JavaScript + TypeScript (where I come from) notoriously has _terrific_ IDE intellisense! This combined with JSDoc comments means that you can do this:
  ![](https://cakebuild.net/assets/img/intellisense-vscode/intellisense-vscode.png)
  the C/C++ ecosystem doesn't quite have the same level. There's _some_ in-code intellisense, but out-of-code documentation really helps.
- Preview what the library does! Having even an auto-generated website like this: https://mesqueeb.github.io/is-what/ is _vastly better_ than having to _download the thing to your PC_ when you are browsing  on your phone.
- Legitimacy. Basically the same as SEO, but more for answering the "should I use this library or the original?" question by _showing_ (not telling)

The website itself doesn't have to be very complicated. Here's an example of what the files  might look like if you use Vitepress https://vitepress.dev/ (Markdown-based static site generator):
![image](https://github.com/btzy/nativefiledialog-extended/assets/61068799/3156096e-76dc-4902-8922-938bfd9d4d9d)
(there's a stackblitz demo in there too that's used as an embed `<iframe>`; ignore that)
https://github.com/jcbhmr/tsx/tree/add-docs-site/docs

**Comment by jcbhmr** [comment]
Here's a prototype of an **extremely simple** plain HTML file that you could drop in the `docs/index.html` spot and serve via GitHub Pages:

[nativefiledialog-extended.md.zip](https://github.com/btzy/nativefiledialog-extended/files/11727953/nativefiledialog-extended.md.zip)

Even this relatively basic thing would be cool!

**Comment by btzy** [comment]
Honestly, I'm not convinced by your list of benefits of having a separate website.

> Google SEO. GitHub project readmes have okish SEO. GitHub wikis have almost zero. They don't seem to be indexed very well

The wiki of this project isn't meant to be the main landing page; the main repo page (https://github.com/btzy/nativefiledialog-extended) is.  The wiki currently contains additional tangential information that is not required for actually using NFDe, and so Google is right not to link directly to it, at least in the top results.  When I Google for "<something> wiki", I expect to get a Wikipedia page, and Google does indeed produce a WIkipedia page as the top result.  "Native File Dialog" is of course the name of the original project, and so you might be looking for _the_ Native File Dialog library, instead of _a_ native file dialog library.  Googling for "native file dialog" (without "wiki") removes the Wikipedia entry.  Furthermore, Googling for "cross platform file dialog" or other generic phrases with similar meaning brings up this library as the first result, so I would argue that we're already enjoying very good visibility on Google.

> Putting more detailed docs outside the readme. This is more of an organizational thing to keep the readme sort of like an "index page" that outsources to the developer-focused "how does this work" (GitHub wiki) and "how do I contribute" (CONTRIBUTING.md) and the user-focused "how do I use this" (docs website) places.

I don't think there is a need for a separate "how does this work" page.  This is not a complex library, and it is fairly obvious what the code needs to do to anyone given the NFDe API and the native platform API, even if they did not read the implementation in this project. "How do I use this" is currently all in the readme.  I intend to add a bit more documentation (in a separate .md file at the top level) about behaviour and invariants relating to the nfdresult_t value, the return value of NFD_GetError(), and the file path returned, though that would still fall under "how do I use this".

> Preview what the library does! Having even an auto-generated website like this: https://mesqueeb.github.io/is-what/ is vastly better than having to download the thing to your PC when you are browsing on your phone.

We already have the basic usage example in the readme, and there are more examples in the `test` directory.  Perhaps we could have a link to that directory from the readme though.  Furthermore, autogeneration is hard in C++, especially because the contract between the user and the library is not explicit; though it can be inferred (by a human) from the header file.  For example, there are some type aliases in the header file that are different depending on the target platform, but users are not supposed to write code that make assumptions on the specific type that the alias refers to.  A good documentation will not contain the alias definition, and tell the user that it is implementation-defined.  Previewing on a phone might be nice, but I think it would require manually writing the documentation for it.  This would be nowhere near as long as the current readme, even including the stuff mentioned in the previous paragraph, so I think it can all go into a single .md file.

> Legitimacy. Basically the same as SEO, but more for answering the "should I use this library or the original?" question by showing (not telling)

Maybe it's different for web developers, but I think a GitHub repository with a well-written readme feels as legitimate as a website.  My favourite C++ unit testing framework (https://github.com/catchorg/Catch2) and benchmarking framework (https://github.com/google/benchmark) use their readmes as the main landing page for their projects.

So yeah, in summary, I don't think there's any additional information that should be put on a website but can't be put in the readme or that one additional file I said I intend to add.  And furthermore, having a website would end up splitting users between the website and the GitHub landing page, and there would end up being confusion as to what to read first, and we'd be repeating ourselves quite a bit.

Remember, this project isn't some complicated framework that performs something indistinguishable from magic.  It is a simple platform abstraction and normalization layer for a specific platform API.  There might be a need for more documentation about how to use all the functions exposed in the header file, but that should go into a separate .md file in the repo, not a separate website.  Many libraries I hold in high regard use their GitHub readme as their main landing page, and I am not convinced of the need to do different.
