### ISSUE TITLE
Confusing build instructions

### ISSUE THREAD

**Issue by ErikPrantare** [btzy/nativefiledialog-extended#19]
I though the build instructions were a bit confusing,
seeing as all I needed to do to use it was to do `add_subdirectory(path-to-nfde)`.
I could take a whack at restructuring the README a bit.
Is the idea that a user can choose between
- adding a subdirectory with cmake
- build a standalone library
?

**Comment by btzy** [comment]
I'm not too sure about CMake, but I think `add_subdirectory()` is usually used for single projects with multiple directories.  When importing NFDe into your project, I think you should be using `target_include_directories()` and `target_link_libraries()` to add it, since that cleanly separates your project from the implementation details of its dependencies.

**Comment by ErikPrantare** [comment]
I can't say I'm an expert in CMake (yet ;^)). But how I did it was basically:
```
add_subdirectory(extern/nfde)
target_link_libraries(MyProgram PRIVATE nfd)
```
So I think as long as the target nfd is properly configured, it should keep MyProgram separated from the implementation details of nfd?

**Comment by btzy** [comment]
I did a bit more research into CMake, and it appears that you are correct.  Please go ahead with restructuring the build instructions; I really appreciate your help!
