### ISSUE TITLE
GTK4 Support

### ISSUE THREAD

**Issue by btzy** [btzy/nativefiledialog-extended#24]
GTK4 has been released, we should eventually support it.

Most of the work has been done in #38 , but the major blocking issue is [this](https://discourse.gnome.org/t/gtk4-gtkfilechooser-show-only-local-files/6363).  In summary, it is not possible to hide non-local files in the GTK4 file chooser (non-local files are those that do not have filepaths, such as resources on the Internet).  We either have to filter the response and show an error message if non-local files are selected, or implement a shim to download those non-local files (not sure if this might be out of scope for NFD?).

Opinions on this issue are welcome.

**Comment by shenlebantongying** [comment]
Sorry for interruption, but GTK is _NOT_ "**the**" native Linux thing, and its file chooser is **_terrible_** (an example reason is that it doesn't have [thumbnails](https://jayfax.neocities.org/mediocrity/gnome-has-no-thumbnails-in-the-file-picker.html) for 18 years).

There is a new `GtkFileChooserNative` which can let users use to _**actual**_ Native file choosers based on their own choice.

https://developer.gnome.org/gtk4/stable/GtkFileChooserNative.html

**Comment by btzy** [comment]
Indeed it is not the native thing on some Linuxes, but it is a *de-facto* standard on the most common ones.  The GTK3 implementation is based on the one in https://github.com/mlabbe/nativefiledialog.  It appears that there is a workaround to make GTK open the KDE dialogs, by doing `GTK_USE_PORTAL=1` when launching the application, though I'm not sure if it requires GtkFileChooserNative.

There is probably also another way, following https://github.com/mlabbe/nativefiledialog/issues/40.

In any case, this should be a separate issue.  I do not intend this GTK4 backend to work differently from the current GTK3 backend, though it may be possible to add some compilation flag in the future to use the native backend.

**Comment by OvermindDL1** [comment]
I noticed this was linked to `nativefiledialog` project and I left a post about the proper way to handle this, see it at:  https://github.com/mlabbe/nativefiledialog/issues/40#issuecomment-912057082

> but it is a de-facto standard on the most common ones

Absolutely not.

> by doing GTK_USE_PORTAL=1 when launching the application, though I'm not sure if it requires GtkFileChooserNative

That option, if enabled in that gtk build, just makes it call out to that same listed dbus endpoint as in the above link instead of calling it natively.  Best to just cut out the middleman and do it correctly so it works on all places properly everywhere for all DE's and you won't need to link to anything odd like kde or gtk or anything.
