### ISSUE TITLE
Update README for CMake support

### ISSUE THREAD

**Issue by blakat360** [btzy/nativefiledialog-extended#7]
I've never used premake and from what I can tell it lets me compile for whatever platform I like. However, my project would ideally have one source which compiles to many different platforms. I am using CMake for my build system.

How would I make a cross platform CMake file of this project?

**Comment by btzy** [comment]
The README is outdated; CMake support was added recently and it should compile (for the native platform) out of the box.

For cross compilation, I think you can add a CMake toolchain file that specifies the target compiler toolchain (since CMake won't be able to automatically figure out which cross compiler you want).  If you have not tried cross compilation before, perhaps this website might help: https://cmake.org/cmake/help/v3.12/manual/cmake-toolchains.7.html

**Comment by btzy** [comment]
Resolved in `c0f5edc5d9804b6a01f4a9b5a61cacb43301ef4f`.
