### ISSUE TITLE
Garbled CJK characters when used on Windows with UTF-8 functions

### ISSUE THREAD

**Issue by Univstar** [btzy/nativefiledialog-extended#89]
As the title states, I compiles and tests nfd-ext on Win 10/11 with UTF-8 functions. All the CJK characters in the returned paths are garbled. How can I fix it?

**Comment by btzy** [comment]
Hi, can you please provide a list of steps to reproduce this?  For example, if you can reproduce it with any of the examples in the repo, you could list the steps needed (including what to name my file) and maybe some screenshots of the output?  Also, it would be good if you can show me what bytes are actually returned, instead of just "garbled".  That might tell me what encoding it is using.

**Comment by Univstar** [comment]
Oh... I have tried to output the code of the characters. It seems that the returned string is correct. The log is wrong due to the incorrect explanation of Windows terminal.
Thanks! I will close this issue.
